package protocol

import (
	"encoding/json"
	"fmt"
	"reflect"
	"sort"
	"strings"
)

// GenerateTypeScriptBindings renders deterministic TypeScript protocol bindings.
func GenerateTypeScriptBindings() (string, error) {
	var builder strings.Builder

	builder.WriteString("// Code generated by sigil app-server generate-ts. DO NOT EDIT.\n")
	builder.WriteString(fmt.Sprintf("export const PROTOCOL_VERSION = %q as const;\n", DefaultProtocolVersion()))
	builder.WriteString(fmt.Sprintf("export const SUPPORTED_PROTOCOL_VERSIONS = %s as const;\n\n", renderStringSliceLiteral(SupportedProtocolVersions())))

	for _, typeInfo := range protocolNamedTypes() {
		renderTypeScriptType(&builder, typeInfo)
		builder.WriteString("\n")
	}

	builder.WriteString("export interface AppServerMethodMap {\n")
	for _, definition := range sortedDefinitions() {
		builder.WriteString(fmt.Sprintf("  %q: {\n", definition.Name))
		builder.WriteString(fmt.Sprintf("    kind: %q;\n", definition.Kind))
		builder.WriteString(fmt.Sprintf("    params: %s;\n", typescriptType(reflect.TypeOf(definition.Params))))
		if definition.Result != nil {
			builder.WriteString(fmt.Sprintf("    result: %s;\n", typescriptType(reflect.TypeOf(definition.Result))))
		}
		builder.WriteString("  };\n")
	}
	builder.WriteString("}\n")

	return builder.String(), nil
}

// GenerateJSONSchemaBundle renders a deterministic JSON Schema bundle for the protocol.
func GenerateJSONSchemaBundle() ([]byte, error) {
	defs := map[string]any{}
	for _, typeInfo := range protocolNamedTypes() {
		defs[typeInfo.Name()] = jsonSchemaForType(typeInfo)
	}

	methods := map[string]any{}
	for _, definition := range sortedDefinitions() {
		methodSchema := map[string]any{
			"type": "object",
			"properties": map[string]any{
				"kind": map[string]any{
					"const": string(definition.Kind),
				},
				"params": jsonSchemaRefOrInline(reflect.TypeOf(definition.Params)),
			},
			"required":             []string{"kind", "params"},
			"additionalProperties": false,
		}
		if definition.Result != nil {
			methodSchema["properties"].(map[string]any)["result"] = jsonSchemaRefOrInline(reflect.TypeOf(definition.Result))
			methodSchema["required"] = []string{"kind", "params", "result"}
		}
		methods[definition.Name] = methodSchema
	}

	bundle := map[string]any{
		"$schema":                   "https://json-schema.org/draft/2020-12/schema",
		"$id":                       "https://sigil.dev/app-server/schema.json",
		"title":                     "Sigil App Server Protocol",
		"type":                      "object",
		"additionalProperties":      false,
		"protocolVersion":           DefaultProtocolVersion(),
		"supportedProtocolVersions": SupportedProtocolVersions(),
		"methods":                   methods,
		"$defs":                     defs,
	}

	encoded, err := json.MarshalIndent(bundle, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("failed to encode JSON Schema bundle; %w", err)
	}

	return append(encoded, '\n'), nil
}

func sortedDefinitions() []MethodDefinition {
	definitions := append([]MethodDefinition(nil), Definitions()...)
	sort.Slice(definitions, func(i int, j int) bool {
		return definitions[i].Name < definitions[j].Name
	})
	return definitions
}

func protocolNamedTypes() []reflect.Type {
	seen := map[reflect.Type]struct{}{}
	for _, definition := range Definitions() {
		collectNamedTypes(seen, reflect.TypeOf(definition.Params))
		collectNamedTypes(seen, reflect.TypeOf(definition.Result))
	}
	collectNamedTypes(seen, reflect.TypeOf(ErrorObject{}))
	collectNamedTypes(seen, reflect.TypeOf(ErrorData{}))

	types := make([]reflect.Type, 0, len(seen))
	for typeInfo := range seen {
		types = append(types, typeInfo)
	}
	sort.Slice(types, func(i int, j int) bool {
		return types[i].Name() < types[j].Name()
	})
	return types
}

func collectNamedTypes(seen map[reflect.Type]struct{}, typeInfo reflect.Type) {
	if typeInfo == nil {
		return
	}
	for typeInfo.Kind() == reflect.Pointer {
		typeInfo = typeInfo.Elem()
	}
	if isTimeType(typeInfo) {
		return
	}

	switch typeInfo.Kind() {
	case reflect.Struct:
		if typeInfo.Name() != "" && typeInfo.PkgPath() != "" {
			if _, ok := seen[typeInfo]; ok {
				return
			}
			seen[typeInfo] = struct{}{}
		}
		for fieldIndex := 0; fieldIndex < typeInfo.NumField(); fieldIndex++ {
			field := typeInfo.Field(fieldIndex)
			collectNamedTypes(seen, field.Type)
		}
	case reflect.Slice, reflect.Array:
		collectNamedTypes(seen, typeInfo.Elem())
	case reflect.Map:
		collectNamedTypes(seen, typeInfo.Elem())
	}
}

func renderTypeScriptType(builder *strings.Builder, typeInfo reflect.Type) {
	switch typeInfo.Kind() {
	case reflect.Struct:
		builder.WriteString(fmt.Sprintf("export interface %s {\n", typeInfo.Name()))
		for fieldIndex := 0; fieldIndex < typeInfo.NumField(); fieldIndex++ {
			field := typeInfo.Field(fieldIndex)
			jsonName, omitEmpty := jsonFieldName(field)
			if jsonName == "" {
				continue
			}
			optional := omitEmpty || field.Type.Kind() == reflect.Pointer
			builder.WriteString(fmt.Sprintf("  %s%s: %s;\n", jsonName, optionalMarker(optional), typescriptType(field.Type)))
		}
		builder.WriteString("}\n")
	default:
		builder.WriteString(fmt.Sprintf("export type %s = %s;\n", typeInfo.Name(), typescriptType(typeInfo)))
	}
}

func optionalMarker(optional bool) string {
	if optional {
		return "?"
	}
	return ""
}

func renderStringSliceLiteral(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, fmt.Sprintf("%q", value))
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

func typescriptType(typeInfo reflect.Type) string {
	if typeInfo == nil {
		return "void"
	}
	for typeInfo.Kind() == reflect.Pointer {
		typeInfo = typeInfo.Elem()
	}
	if isTimeType(typeInfo) {
		return "string"
	}
	if typeInfo.Name() != "" && typeInfo.PkgPath() != "" && typeInfo.Kind() == reflect.Struct {
		return typeInfo.Name()
	}

	switch typeInfo.Kind() {
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number"
	case reflect.String:
		return "string"
	case reflect.Interface:
		return "unknown"
	case reflect.Slice, reflect.Array:
		return typescriptType(typeInfo.Elem()) + "[]"
	case reflect.Map:
		return fmt.Sprintf("Record<string, %s>", typescriptType(typeInfo.Elem()))
	case reflect.Struct:
		return typeInfo.Name()
	default:
		return "unknown"
	}
}

func jsonSchemaForType(typeInfo reflect.Type) any {
	if typeInfo == nil {
		return map[string]any{}
	}
	for typeInfo.Kind() == reflect.Pointer {
		typeInfo = typeInfo.Elem()
	}
	if isTimeType(typeInfo) {
		return map[string]any{
			"type":   "string",
			"format": "date-time",
		}
	}

	switch typeInfo.Kind() {
	case reflect.Bool:
		return map[string]any{"type": "boolean"}
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return map[string]any{"type": "integer"}
	case reflect.Float32, reflect.Float64:
		return map[string]any{"type": "number"}
	case reflect.String:
		return map[string]any{"type": "string"}
	case reflect.Interface:
		return map[string]any{}
	case reflect.Slice, reflect.Array:
		return map[string]any{
			"type":  "array",
			"items": jsonSchemaRefOrInline(typeInfo.Elem()),
		}
	case reflect.Map:
		return map[string]any{
			"type":                 "object",
			"additionalProperties": jsonSchemaRefOrInline(typeInfo.Elem()),
		}
	case reflect.Struct:
		properties := map[string]any{}
		required := []string{}
		for fieldIndex := 0; fieldIndex < typeInfo.NumField(); fieldIndex++ {
			field := typeInfo.Field(fieldIndex)
			jsonName, omitEmpty := jsonFieldName(field)
			if jsonName == "" {
				continue
			}
			properties[jsonName] = jsonSchemaRefOrInline(field.Type)
			if !omitEmpty && field.Type.Kind() != reflect.Pointer {
				required = append(required, jsonName)
			}
		}
		sort.Strings(required)
		schema := map[string]any{
			"type":                 "object",
			"properties":           properties,
			"additionalProperties": false,
		}
		if len(required) > 0 {
			schema["required"] = required
		}
		return schema
	default:
		return map[string]any{}
	}
}

func jsonSchemaRefOrInline(typeInfo reflect.Type) any {
	if typeInfo == nil {
		return map[string]any{}
	}
	for typeInfo.Kind() == reflect.Pointer {
		typeInfo = typeInfo.Elem()
	}
	if isTimeType(typeInfo) {
		return jsonSchemaForType(typeInfo)
	}
	if typeInfo.Name() != "" && typeInfo.PkgPath() != "" && typeInfo.Kind() == reflect.Struct {
		return map[string]any{
			"$ref": "#/$defs/" + typeInfo.Name(),
		}
	}
	return jsonSchemaForType(typeInfo)
}

func jsonFieldName(field reflect.StructField) (string, bool) {
	tag := field.Tag.Get("json")
	if tag == "-" {
		return "", false
	}
	if tag == "" {
		return field.Name, false
	}

	parts := strings.Split(tag, ",")
	name := parts[0]
	if name == "" {
		name = field.Name
	}

	for _, part := range parts[1:] {
		if part == "omitempty" {
			return name, true
		}
	}
	return name, false
}

func isTimeType(typeInfo reflect.Type) bool {
	return typeInfo != nil && typeInfo.PkgPath() == "time" && typeInfo.Name() == "Time"
}
